// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoM6dviR9Vctnm5U-6n5bCvDiZ3OK6tec',
    appId: '1:674850950576:web:placeholder',
    messagingSenderId: '674850950576',
    projectId: 'nile-quest-20d61',
    authDomain: 'nile-quest-20d61.firebaseapp.com',
    storageBucket: 'nile-quest-20d61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoM6dviR9Vctnm5U-6n5bCvDiZ3OK6tec',
    appId: '1:674850950576:android:e09bad5d633f5b40595a75',
    messagingSenderId: '674850950576',
    projectId: 'nile-quest-20d61',
    storageBucket: 'nile-quest-20d61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoM6dviR9Vctnm5U-6n5bCvDiZ3OK6tec',
    appId: '1:674850950576:ios:placeholder',
    messagingSenderId: '674850950576',
    projectId: 'nile-quest-20d61',
    storageBucket: 'nile-quest-20d61.firebasestorage.app',
    iosBundleId: 'com.nilequest.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoM6dviR9Vctnm5U-6n5bCvDiZ3OK6tec',
    appId: '1:674850950576:ios:placeholder',
    messagingSenderId: '674850950576',
    projectId: 'nile-quest-20d61',
    storageBucket: 'nile-quest-20d61.firebasestorage.app',
    iosBundleId: 'com.nilequest.app',
  );
}
